on:
  push:
    branches:
      - main

name: Build & Deploy 🚀

jobs:
  build_wasm:
    name: Build wasm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: wasm-pack build --release
      - uses: actions/upload-artifact@v2
        with:
          name: wasm-package
          path: pkg
          if-no-files-found: error

  build_site:
    name: build website
    needs: build_wasm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: www
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: actions/download-artifact@v2
        with:
          name: wasm-package
          path: pkg
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: www/dist
          if-no-files-found: error

  deploy_website:
    name: deploy website
    needs: build_site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: website
          path: dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
